modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="chunklimiter"
version="1.0.0"
displayName="ChunkLimiter"
logoFile ="logo.png"
authors="Vecoo"
description="A mod that adds a block limit per chunk."

[[dependencies.chunklimiter]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.chunklimiter]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"