modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="chunklimiter"
version="1.2.0"
displayName="ChunkLimiter"
logoFile ="logo.png"
authors="Vecoo"
description="Mod that adds a customizable limit on the number of blocks per chunk."

[[dependencies.chunklimiter]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.chunklimiter]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"

[[dependencies.chunklimiter]]
modId="extralib"
mandatory=true
versionRange="[1.3,)"
ordering="AFTER"
side="BOTH"