modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"

[[mods]]
modId = "chunklimiter"
version = "1.3.1"
displayName = "ChunkLimiter"
logoFile = "logo.png"
authors = "Vecoo"
description = "Mod that adds a customizable limit on the number of blocks per chunk."

[[dependencies.chunklimiter]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chunklimiter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chunklimiter]]
modId = "extralib"
mandatory = true
versionRange = "[1.5,)"
ordering = "NONE"
side = "BOTH"